### ISSUE TITLE
Can't find manage.py

### ISSUE THREAD

**Issue by angrybacon** [gopar/django-manage#3]
Sometimes `manage.py` doesn't live at Projectile's root directory. I think `django-manage-root` should be overwritten by some variable when set. That way, we could set this variable from `.dir-locals.el`. Thoughts?

**Comment by gopar** [comment]
Yeah, I've had this issue sometimes too. I plan on doing something like this, but right now I'm kinda tied up. 

A Pull Request would be awesome ;)
